branch-defaults:
  main:
    environment: gdscys-resume-ai
    group_suffix: null
global:
  application_name: gdscys-resume-ai
  branch: null
  default_ec2_keyname: gdsc-yonsei-resume-ai
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
