import { StyleTypes } from "@types";

const defaultThemeLight: StyleTypes.ColorTheme = {
  primary: "#375CA8",
  onPrimary: "#FFFFFF",
  primaryContainer: "#D9E2FF",
  onPrimaryContainer: "#001945",
  primaryFixed: "#D9E2FF",
  onPrimaryFixed: "#001945",
  primaryFixedDim: "#B0C6FF",
  onPrimaryFixedVariant: "#19438F",
  secondary: "#2E5DA8",
  onSecondary: "#FFFFFF",
  secondaryContainer: "#D7E2FF",
  onSecondaryContainer: "#001A40",
  secondaryFixed: "#D7E2FF",
  onSecondaryFixed: "#001A40",
  secondaryFixedDim: "#ACC7FF",
  onSecondaryFixedVariant: "#08458E",
  tertiary: "#235FA6",
  onTertiary: "#FFFFFF",
  tertiaryContainer: "#D5E3FF",
  onTertiaryContainer: "#001B3B",
  tertiaryFixed: "#D5E3FF",
  onTertiaryFixed: "#001B3B",
  tertiaryFixedDim: "#A7C8FF",
  onTertiaryFixedVariant: "#004788",
  error: "#AF2D33",
  onError: "#FFFFFF",
  errorContainer: "#FFDAD8",
  onErrorContainer: "#410006",
  outline: "#757780",
  background: "#FEFBFF",
  onBackground: "#1B1B1F",
  surface: "#FBF8FD",
  onSurface: "#1B1B1F",
  surfaceVariant: "#E1E2EC",
  onSurfaceVariant: "#44464F",
  inverseSurface: "#303034",
  inverseOnSurface: "#F2F0F4",
  inversePrimary: "#B0C6FF",
  shadow: "#000000",
  surfaceTint: "#375CA8",
  outlineVariant: "#C5C6D0",
  scrim: "#000000",
  surfaceContainerHighest: "#E3E2E6",
  surfaceContainerHigh: "#E9E7EC",
  surfaceContainer: "#EFEDF1",
  surfaceContainerLow: "#F5F3F7",
  surfaceContainerLowest: "#FFFFFF",
  surfaceBright: "#FBF8FD",
  surfaceDim: "#DBD9DD",
} as const;

export { defaultThemeLight };
