import { StyleTypes } from "@types";

const defaultThemeLight: StyleTypes.ColorTheme = {
  primary: "#6750A4",
  onPrimary: "#FFFFFF",
  primaryContainer: "#EADDFF",
  onPrimaryContainer: "#21005D",
  primaryFixed: "#EADDFF",
  onPrimaryFixed: "#21005D",
  primaryFixedDim: "#D0BCFF",
  onPrimaryFixedVariant: "#4F378B",
  secondary: "#625B71",
  onSecondary: "#FFFFFF",
  secondaryContainer: "#E8DEF8",
  onSecondaryContainer: "#1D192B",
  secondaryFixed: "#E8DEF8",
  onSecondaryFixed: "#1D192B",
  secondaryFixedDim: "#CCC2DC",
  onSecondaryFixedVariant: "#4A4458",
  tertiary: "#7D5260",
  onTertiary: "#FFFFFF",
  tertiaryContainer: "#FFD8E4",
  onTertiaryContainer: "#31111D",
  tertiaryFixed: "#FFD8E4",
  onTertiaryFixed: "#31111D",
  tertiaryFixedDim: "#EFB8C8",
  onTertiaryFixedVariant: "#633B48",
  error: "#B3261E",
  onError: "#FFFFFF",
  errorContainer: "#F9DEDC",
  onErrorContainer: "#410E0B",
  outline: "#79747E",
  background: "#FEF7FF",
  onBackground: "#1D1B20",
  surface: "#FEF7FF",
  onSurface: "#1D1B20",
  surfaceVariant: "#E7E0EC",
  onSurfaceVariant: "#49454F",
  inverseSurface: "#322F35",
  inverseOnSurface: "#F5EFF7",
  inversePrimary: "#D0BCFF",
  shadow: "#000000",
  surfaceTint: "#6750A4",
  outlineVariant: "#CAC4D0",
  scrim: "#000000",
  surfaceContainerHighest: "#E6E0E9",
  surfaceContainerHigh: "#ECE6F0",
  surfaceContainer: "#F3EDF7",
  surfaceContainerLow: "#F7F2FA",
  surfaceContainerLowest: "#FFFFFF",
  surfaceBright: "#FEF7FF",
  surfaceDim: "#DED8E1",
} as const;

export { defaultThemeLight };
